name: Deploy Allure Report to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'allure-report/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 这一行是关键，必须有写权限
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          force_orphan: true
          enable_jekyll: false
